# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - .build
  - Carthage
  - Tests/LinuxMain.swift
  - Tests/IdentifierTests/XCTestManifests.swift

trailing_comma:
  mandatory_comma: true
