# Configuration for Travis (https://travis-ci.com)

os: osx
osx_image: xcode11
language: swift

stages:
  - pretest
  - test

jobs:
  include:
    - stage: pretest
      name: Validate Linux test manifest
      install: swift test --generate-linuxmain --disable-automatic-resolution
      script: git diff --exit-code

    - &spm
      stage: test
      name: SPM @ Xcode 11 / macOS
      script: swift test --disable-automatic-resolution
    - <<: *spm
      name: SPM 5.1 / Linux
      os: linux
      language: generic
      env: SWIFT_VERSION=5.1
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

    - &cocoapods
      name: CocoaPods & Xcode 11 / pod lib lint
      script: pod lib lint

    - &carthage
      name: Carthage & Xcode 11 / carthage build --archive
      script: carthage build --archive

    - &xcode
      name: Xcode 11 / macOS
      xcode_project: Identifier.xcodeproj
      xcode_scheme: Identifier
      xcode_destination: 'platform=macOS'
    - <<: *xcode
      name: Xcode 11 / iOS
      xcode_destination: 'OS=12.2,name=iPhone SE'
    - <<: *xcode
      name: Xcode 11 / tvOS
      xcode_destination: 'OS=12.2,name=Apple TV'
    - <<: *xcode
      name: Xcode 11 / watchOS
      xcode_destination: 'OS=5.2,name=Apple Watch Series 2 - 38mm'
      script: set -o pipefail && xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$TRAVIS_XCODE_DESTINATION" build | xcpretty

    - name: Gather test coverage
      xcode_project: Identifier.xcodeproj
      xcode_scheme: Identifier-Package
      xcode_destination: 'platform=macOS'
      before_install:
        - rm -r Identifier.xcodeproj
        - echo "@available(*, unavailable) func doNothing() {}" > Sources/Identifier/_CoverageHack.swift # Add a second source file to appease Codecov processing
      install: swift package generate-xcodeproj --enable-code-coverage
      after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
