# Configuration for Travis (https://travis-ci.com)

os: osx
osx_image: xcode10.2
language: swift

stages:
  - pretest
  - test

jobs:
  include:
    - stage: pretest
      name: Validate Linux test manifest
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - &spm
      stage: test
      name: macOS / SPM 5.0 / Swift 5.0
      script: swift test -Xswiftc -swift-version -Xswiftc 5
    - <<: *spm
      name: Linux / SPM 5.0 / Swift 5.0
      os: linux
      language: generic
      env: SWIFT_VERSION=5.0 
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

    - &xcode
      name: macOS / Xcode 10.2 / Swift 5.0
      xcode_project: Identifier.xcodeproj
      xcode_scheme: Identifier-Package
      xcode_destination: 'platform=macOS'
      install: swift package generate-xcodeproj --enable-code-coverage
      after_success: bash <(curl -s https://codecov.io/bash)
    - <<: *xcode
      name: iOS / Xcode 10.2 / Swift 5.0
      xcode_destination: 'OS=12.2,name=iPhone SE'
    - <<: *xcode
      name: tvOS / Xcode 10.2 / Swift 5.0
      xcode_destination: 'OS=12.2,name=Apple TV'

notifications:
  email: false
