# Configuration for Travis (https://travis-ci.com)

os: osx
osx_image: xcode10.2
language: swift

stages:
  - pretest
  - test

jobs:
  include:
    - stage: pretest
      name: Validate Linux test manifest
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - &spm
      stage: test
      name: macOS / SPM 5.0 / Swift 5.0
      script: swift test -Xswiftc -swift-version -Xswiftc 5
    - <<: *spm
      name: Linux / SPM 5.0 / Swift 5.0
      os: linux
      language: generic
      env: SWIFT_VERSION=5.0 
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

    - &xcode
      name: macOS / Xcode 10.2 / Swift 5.0
      xcode_project: Identifier.xcodeproj
      xcode_scheme: Identifier
      xcode_destination: 'platform=macOS'
      before_install: echo "@available(*, unavailable) func doNothing() {}" > Sources/Identifier/_CoverageHack.swift # Add a second source file to appease Codecov processing
      after_success: bash <(curl -s https://codecov.io/bash)
    - <<: *xcode
      name: iOS / Xcode 10.2 / Swift 5.0
      xcode_destination: 'OS=12.2,name=iPhone SE'
    - <<: *xcode
      name: tvOS / Xcode 10.2 / Swift 5.0
      xcode_destination: 'OS=12.2,name=Apple TV'
    - <<: *xcode
      name: watchOS / Xcode 10.2 / Swift 5.0
      xcode_destination: 'OS=5.2,name=Apple Watch Series 2 - 38mm'
      script: set -o pipefail && xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$TRAVIS_XCODE_DESTINATION" build | xcpretty

notifications:
  email: false
