#if !canImport(ObjectiveC)
import XCTest

extension IdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IdentifierTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
        ("testEquality", testEquality),
        ("testInitWithUUID", testInitWithUUID),
        ("testRandomIdentifier", testRandomIdentifier),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IdentifierTests.__allTests__IdentifierTests),
    ]
}
#endif
